DOCKER_ALPINE_STEM = docker-alpine
DOCKER_ALPINE = $(DOCKER_ALPINE_STEM).gz
$(DOCKER_ALPINE)_PATH = $(PLATFORM_PATH)/$(DOCKER_ALPINE_STEM)

SONIC_SIMPLE_DOCKER_IMAGES += $(DOCKER_ALPINE)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_ALPINE)

$(DOCKER_ALPINE)_CONTAINER_NAME = docker-alpine
$(DOCKER_ALPINE)_RUN_OPT += --net=host --privileged -t