# sonic broadcom one image installer

SONIC_ONE_IMAGE = sonic-broadcom.bin
$(SONIC_ONE_IMAGE)_MACHINE = broadcom
$(SONIC_ONE_IMAGE)_IMAGE_TYPE = onie
$(SONIC_ONE_IMAGE)_INSTALLS += $(BRCM_OPENNSL_KERNEL)
$(SONIC_ONE_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_ONE_IMAGE)_LAZY_INSTALLS += $(ACCTON_AS4630_54PE_PLATFORM_MODULE)
#$(SONIC_ONE_IMAGE)_INSTALLS += $(HELLOMAKE) 
#$(SONIC_ONE_IMAGE)_INSTALLS += $(HELLOWORLD)
							   
ifeq ($(INSTALL_DEBUG_TOOLS),y)
$(SONIC_ONE_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_DBG_IMAGES)
$(SONIC_ONE_IMAGE)_DOCKERS += $(filter-out $(patsubst %-$(DBG_IMAGE_MARK).gz,%.gz, $(SONIC_INSTALL_DOCKER_DBG_IMAGES)), $(SONIC_INSTALL_DOCKER_IMAGES))
else
$(SONIC_ONE_IMAGE)_DOCKERS = $(SONIC_INSTALL_DOCKER_IMAGES)
endif

SONIC_INSTALLERS += $(SONIC_ONE_IMAGE)
$(SONIC_ONE_IMAGE)_INSTALLS += $(UMIQUSB)
$(SONIC_ONE_IMAGE)_INSTALLS += $(HELLOAUTOTOOLS)
